
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: service-hi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: provider8005
    prefer-ip-address: true

server:
  port: 8005

info:
 app:
  name: amber-cloud-dept-8001
 company:
  name: www.amber.com
 build:
  artifactId: $project.artifactId$
  version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  profiles: test
  application:
    name: service-hi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: provider8015
    prefer-ip-address: true

server:
  port: 8015



info:
 app:
  name: amber-cloud-dept-8001
 company:
  name: www.amber.com
 build:
  artifactId: $project.artifactId$
  version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'
